# Generated by Django 4.1.5 on 2023-01-06 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotlight',
            name='name',
        ),
    ]
