# Generated by Django 4.1.5 on 2023-01-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_spotlight_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotlight',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
